### ISSUE TITLE
Please comment to be added as collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/welwyn-dec-2016#1]
:wave: class, please comment below so I can add you as **collaborator**.

**Comment by ghost** [comment]
This is a comment :smile_cat: :+1: :ear_of_rice:

**Comment by kenwayp** [comment]
Hello from Philip

**Comment by reddivgit** [comment]
hello

**Comment by gowerc** [comment]
This is another comment 👍  :c# 🏃  🏖  🍸  😄  🔢 
Apparently we can edit each other's comments!

**Comment by efoster** [comment]
# HELLO from me!

**Comment by luffm** [comment]
こんにちは！

**Comment by BhupendraMistry** [comment]
Can you categorise the idea ?

**Comment by GuiyuanLei** [comment]
Is "create repositories" same as "create projects"?

**Comment by grundyd** [comment]
Morning!

**Comment by ruchiups** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @kieranmartin, @kenwayp, @reddivgit, @CG1122, @efoster, @luffm, @BhupendraMistry, @GuiyuanLei, @grundyd, and @ruchiups are now  repository collaborators. :balloon:

**Comment by githubteacher** [comment]
@stoe can you look at this ✨ ing idea, please?

**Comment by luffm** [comment]
@luffm message to myself

**Comment by stoe** [comment]
hello y'all

**Comment by efoster** [comment]
Hello @githubteacher. please read this.

**Comment by ruchiups** [comment]
@githubteacher where do I find emojis?

**Comment by gowerc** [comment]
@ruchiups   press ":"  then it should autocomplete 😄  🐈 🌞 

Not enough emojis :+1: :-1: :8ball: :abcd: :baby: :cactus: :dagger: :ear: :face_with_head_bandage: :gabon: 
:eritrea:

**Comment by ruchiups** [comment]
@CG1122 :+1:

**Comment by BhupendraMistry** [comment]
@reddivgit  test
